/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.github.bodin;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;
import org.springframework.web.servlet.function.RouterFunction;
import org.springframework.web.servlet.function.RouterFunctions;
import org.springframework.web.servlet.function.ServerResponse;

import java.util.*;

import static org.springframework.web.servlet.function.ServerResponse.ok;

@SpringBootApplication
public class Application {

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }

    @Bean
    public RouterFunction<ServerResponse> endpoints() {
        final Set<String> openCircuits = Collections.synchronizedSet(new HashSet<>());
        return RouterFunctions.route()
                .GET("/circuits", req ->
                        ok().body(openCircuits)
                ).PUT("/circuits/{name}", req -> {
                    openCircuits.add(req.pathVariable("name"));
                    return ok().body(openCircuits);
                }).DELETE("/circuits/{name}", req -> {
                    openCircuits.remove(req.pathVariable("name"));
                    return ok().body(openCircuits);
                })
            .build();
    }
}