/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.github.bodin;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

class CircuitTest {
    @Test void testAlwaysOpenCircuit() {
        Circuit alwaysOpen = new StaticCircuit(true);

        assertTrue(alwaysOpen.isOpen(), "StaticCircuit should return 'true'");
        assertFalse(alwaysOpen.isClosed(), "StaticCircuit should return 'false'");
    }

    @Test void testAlwaysClosedCircuit() {
        Circuit alwaysOpen = new StaticCircuit(false);

        assertFalse(alwaysOpen.isOpen(), "StaticCircuit should return 'false'");
        assertTrue(alwaysOpen.isClosed(), "StaticCircuit should return 'true'");
    }
}
