/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.github.bodin;

import org.junit.jupiter.api.Test;

import java.util.Arrays;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

class DynamicCircuitTest {
    @Test void testDynamicCircuit() {
        DynamicCircuitService service = new DynamicCircuitService();
        Circuit dynamicCircuit = service.create("dynamic-circuit");

        assertFalse(service.isOpen("dynamic-circuit"));
        assertFalse(dynamicCircuit.isOpen());

        service.reset(List.of("foo"));

        assertFalse(service.isOpen("dynamic-circuit"));
        assertFalse(dynamicCircuit.isOpen());

        service.reset(Arrays.asList("foo", "dynamic-circuit"));

        assertTrue(service.isOpen("dynamic-circuit"));
        assertTrue(dynamicCircuit.isOpen());

        service.reset(List.of("foo"));

        assertFalse(service.isOpen("dynamic-circuit"));
        assertFalse(dynamicCircuit.isOpen());
    }
}
